import React from 'react';
import Header from '../components/Header';
import Footer from '../components/Footer';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-[#0c0c0b] text-[#f0ede8] font-sans pt-[80px] flex flex-col justify-between selection:bg-[#e8541a] selection:text-white">
      <Header />
      
      <main className="max-w-4xl mx-auto px-6 md:px-12 py-12 flex-1">
        <h1 className="text-3xl md:text-4xl font-bold tracking-tight mb-4">Terms of Service</h1>
        <p className="text-[#a09d98] text-sm mb-8 pb-8 border-b border-[#272521]">
          Effective Date: July 4, 2026
        </p>
        
        <div className="space-y-8 text-[#d0cdc8] leading-relaxed text-base">
          <section>
            <h2 className="text-xl font-semibold text-[#f0ede8] mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing and using SankeyLoop (the "Service" or "Website" located at sankeyloop.com), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our web application or services.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f0ede8] mb-3">2. Description of Service</h2>
            <p>
              SankeyLoop provides a free, browser-based, client-side web tool for generating, customizing, and exporting Sankey flow diagrams, along with educational guides and tutorials. The Service is provided "as is" and "as available" without warranties of any kind.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f0ede8] mb-3">3. Intellectual Property &amp; Diagram Ownership</h2>
            <p className="mb-3">
              **You own what you create.** All diagrams, SVG exports, PNG images, and video animations generated using your data in the SankeyLoop editor remain your sole intellectual property.
            </p>
            <p>
              You are free to use diagrams generated by SankeyLoop for personal, academic, commercial, internal corporate presentations, and published research without requiring separate licensing fees or mandatory royalties. Attribution to SankeyLoop is appreciated but not legally mandatory.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f0ede8] mb-3">4. Acceptable Use Policy</h2>
            <p className="mb-2">When using SankeyLoop, you agree not to:</p>
            <ul className="list-disc pl-6 space-y-1 text-[#a09d98]">
              <li>Use the Service for any unlawful, fraudulent, or malicious activities.</li>
              <li>Attempt to reverse engineer, disrupt, or overload our hosting infrastructure or APIs.</li>
              <li>Deploy automated scraping bots or abuse our public endpoints in a manner that degrades performance for other users.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f0ede8] mb-3">5. Disclaimer of Warranties &amp; Limitation of Liability</h2>
            <p className="mb-3">
              SankeyLoop is a visualization aid. While we strive for mathematical precision and visual accuracy in flow calculations, we make no guarantees regarding the suitability of the diagrams for critical safety, financial auditing, or engineering compliance decisions.
            </p>
            <p>
              In no event shall SankeyLoop, its creators, or its contributors be liable for any direct, indirect, incidental, special, consequential, or exemplary damages arising out of your use of or inability to use the Service or diagrams.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f0ede8] mb-3">6. Third-Party Links &amp; Advertisements</h2>
            <p>
              The Service may contain links to third-party websites or display advertisements served by Google AdSense and other advertising partners. We do not endorse or assume responsibility for the content, privacy policies, or practices of any third-party websites or services.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f0ede8] mb-3">7. Modifications to Terms</h2>
            <p>
              We reserve the right to modify or replace these Terms at our discretion at any time. Your continued use of the Service after any changes constitutes acceptance of the new Terms of Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-[#f0ede8] mb-3">8. Contact Information</h2>
            <p>
              For any questions regarding these Terms of Service, please reach out to us at <a href="mailto:tomsanzf@gmail.com" className="text-[#ff813f] underline hover:text-white">tomsanzf@gmail.com</a>.
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
