import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const distDir = path.resolve(__dirname, '../dist');

// Read the base index.html generated by Vite
const baseHtmlPath = path.join(distDir, 'index.html');
if (!fs.existsSync(baseHtmlPath)) {
  console.error('Error: dist/index.html not found. Run vite build before prerendering.');
  process.exit(1);
}

const baseHtml = fs.readFileSync(baseHtmlPath, 'utf-8');

const pages = [
  {
    route: '/learn',
    title: 'The SankeyLoop Learning Hub - Tutorials & Guides',
    desc: 'Master the art and science of quantitative flow modeling. Comprehensive guides on thermodynamic heat balances, corporate financial accounting, and visualization best practices.',
    content: `
      <header style="padding: 24px 48px; background: #0c0c0b; border-bottom: 1px solid #272521; color: #f0ede8; font-family: sans-serif; display: flex; justify-content: space-between; align-items: center;">
        <a href="/" style="font-size: 18px; font-weight: bold; color: #f0ede8; text-decoration: none;">Sankey<span style="color: #e8541a;">Loop</span></a>
        <nav style="display: flex; gap: 20px;">
          <a href="/" style="color: #a09d98; text-decoration: none; font-size: 14px;">Home</a>
          <a href="/learn" style="color: #e8541a; text-decoration: none; font-size: 14px;">Tutorials &amp; Guides</a>
          <a href="/about" style="color: #a09d98; text-decoration: none; font-size: 14px;">About</a>
          <a href="/privacy" style="color: #a09d98; text-decoration: none; font-size: 14px;">Privacy</a>
          <a href="/contact" style="color: #a09d98; text-decoration: none; font-size: 14px;">Contact</a>
          <a href="/app" style="color: #fff; background: #e8541a; padding: 6px 14px; border-radius: 4px; text-decoration: none; font-size: 14px;">Open Editor →</a>
        </nav>
      </header>
      <main style="padding: 48px; max-width: 1000px; margin: 0 auto; color: #f0ede8; font-family: sans-serif; line-height: 1.6;">
        <div style="text-align: center; margin-bottom: 48px;">
          <span style="color: #ff813f; font-size: 12px; font-weight: bold; text-transform: uppercase; letter-spacing: 1px;">Knowledge Base &amp; Tutorials</span>
          <h1 style="font-size: 42px; margin-top: 12px; margin-bottom: 16px;">The SankeyLoop Learning Hub</h1>
          <p style="color: #a09d98; font-size: 18px; max-width: 800px; margin: 0 auto;">Master the art and science of quantitative flow modeling. Comprehensive guides on thermodynamic heat balances, corporate financial accounting, and visualization best practices.</p>
        </div>
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 32px; margin-bottom: 64px;">
          <div style="background: #161513; border: 1px solid #272521; padding: 32px; border-radius: 12px;">
            <span style="color: #ff813f; font-size: 12px; font-weight: bold;">Fundamentals</span>
            <h2 style="font-size: 24px; margin-top: 8px; margin-bottom: 12px;"><a href="/learn/ultimate-guide-sankey-diagrams" style="color: #f0ede8; text-decoration: none;">The Ultimate Guide to Sankey Diagrams: History, Mathematics, and Best Practices</a></h2>
            <p style="color: #a09d98; font-size: 15px; margin-bottom: 20px;">Explore the rich history, mathematical foundations of graph theory, and modern best practices for building clean, crossing-free flowcharts across scientific and industrial disciplines.</p>
            <a href="/learn/ultimate-guide-sankey-diagrams" style="color: #e8541a; font-weight: bold; font-size: 14px; text-decoration: none;">Read Full Guide →</a>
          </div>
          <div style="background: #161513; border: 1px solid #272521; padding: 32px; border-radius: 12px;">
            <span style="color: #ff813f; font-size: 12px; font-weight: bold;">Engineering</span>
            <h2 style="font-size: 24px; margin-top: 8px; margin-bottom: 12px;"><a href="/learn/energy-efficiency-heat-balance" style="color: #f0ede8; text-decoration: none;">Sankey Diagrams for Energy Efficiency &amp; Thermodynamic Heat Balances</a></h2>
            <p style="color: #a09d98; font-size: 15px; margin-bottom: 20px;">How thermal engineers use Sankey diagrams to model boiler enthalpy flows, waste heat recovery, exergy destruction, and HVAC building energy balances.</p>
            <a href="/learn/energy-efficiency-heat-balance" style="color: #e8541a; font-weight: bold; font-size: 14px; text-decoration: none;">Read Full Guide →</a>
          </div>
          <div style="background: #161513; border: 1px solid #272521; padding: 32px; border-radius: 12px;">
            <span style="color: #ff813f; font-size: 12px; font-weight: bold;">Finance</span>
            <h2 style="font-size: 24px; margin-top: 8px; margin-bottom: 12px;"><a href="/learn/financial-cash-flow-budgeting" style="color: #f0ede8; text-decoration: none;">Visualizing Corporate Cash Flow &amp; P&amp;L Statements with Sankey Diagrams</a></h2>
            <p style="color: #a09d98; font-size: 15px; margin-bottom: 20px;">Transform GAAP income statements and SaaS revenue funnels into clear financial waterfalls. Model gross revenue, COGS, R&amp;D overhead, and net margin retention.</p>
            <a href="/learn/financial-cash-flow-budgeting" style="color: #e8541a; font-weight: bold; font-size: 14px; text-decoration: none;">Read Full Guide →</a>
          </div>
          <div style="background: #161513; border: 1px solid #272521; padding: 32px; border-radius: 12px;">
            <span style="color: #ff813f; font-size: 12px; font-weight: bold;">Documentation</span>
            <h2 style="font-size: 24px; margin-top: 8px; margin-bottom: 12px;"><a href="/learn/sankeyloop-user-manual" style="color: #f0ede8; text-decoration: none;">SankeyLoop Editor User Manual &amp; Technical Documentation</a></h2>
            <p style="color: #a09d98; font-size: 15px; margin-bottom: 20px;">Complete documentation for SankeyLoop: natural language syntax rules, Excel drag-and-drop table formatting, custom node positioning, and vector export options.</p>
            <a href="/learn/sankeyloop-user-manual" style="color: #e8541a; font-weight: bold; font-size: 14px; text-decoration: none;">Read Full Manual →</a>
          </div>
        </div>
      </main>
      <footer style="padding: 32px 48px; background: #0c0c0b; border-top: 1px solid #272521; color: #a09d98; font-family: sans-serif; font-size: 12px; text-align: center;">
        <p>© 2026 SankeyLoop. All rights reserved. <a href="/privacy" style="color: #a09d98;">Privacy Policy</a> | <a href="/terms" style="color: #a09d98;">Terms of Service</a> | <a href="/about" style="color: #a09d98;">About Us</a> | <a href="/contact" style="color: #a09d98;">Contact</a></p>
      </footer>
    `
  },
  {
    route: '/learn/ultimate-guide-sankey-diagrams',
    title: 'The Ultimate Guide to Sankey Diagrams: History, Mathematics, and Best Practices - SankeyLoop',
    desc: 'Explore the rich history, mathematical foundations of graph theory, and modern best practices for building clean, quantitative Sankey flow diagrams across scientific disciplines.',
    content: `
      <header style="padding: 24px 48px; background: #0c0c0b; border-bottom: 1px solid #272521; color: #f0ede8; font-family: sans-serif; display: flex; justify-content: space-between; align-items: center;">
        <a href="/" style="font-size: 18px; font-weight: bold; color: #f0ede8; text-decoration: none;">Sankey<span style="color: #e8541a;">Loop</span></a>
        <nav style="display: flex; gap: 20px;">
          <a href="/" style="color: #a09d98; text-decoration: none; font-size: 14px;">Home</a>
          <a href="/learn" style="color: #e8541a; text-decoration: none; font-size: 14px;">Tutorials &amp; Guides</a>
          <a href="/about" style="color: #a09d98; text-decoration: none; font-size: 14px;">About</a>
          <a href="/privacy" style="color: #a09d98; text-decoration: none; font-size: 14px;">Privacy</a>
          <a href="/contact" style="color: #a09d98; text-decoration: none; font-size: 14px;">Contact</a>
          <a href="/app" style="color: #fff; background: #e8541a; padding: 6px 14px; border-radius: 4px; text-decoration: none; font-size: 14px;">Open Editor →</a>
        </nav>
      </header>
      <main style="padding: 48px; max-width: 900px; margin: 0 auto; color: #f0ede8; font-family: sans-serif; line-height: 1.7;">
        <div style="margin-bottom: 32px;"><a href="/learn" style="color: #ff813f; text-decoration: none; font-size: 14px;">← Back to Learning Hub</a></div>
        <span style="color: #ff813f; font-size: 12px; font-weight: bold; text-transform: uppercase;">Fundamentals • 12 min read</span>
        <h1 style="font-size: 40px; margin-top: 12px; margin-bottom: 24px;">The Ultimate Guide to Sankey Diagrams: History, Mathematics, and Best Practices</h1>
        <p style="color: #a09d98; font-size: 18px; margin-bottom: 40px;">Explore the rich history, mathematical foundations of graph theory, and modern best practices for building clean, crossing-free flowcharts across scientific and industrial disciplines.</p>
        
        <h2 style="font-size: 26px; margin-top: 40px; margin-bottom: 16px;">1. What is a Sankey Diagram?</h2>
        <p style="color: #a09d98; margin-bottom: 20px;">A Sankey diagram is a specialized type of quantitative flow diagram in which the width of the arrows or bands is proportionally scaled to the flow quantity. Whether you are mapping energy consumption across a manufacturing facility, tracing material distribution through a global supply chain, or illustrating user drop-off bottlenecks in software analytics, Sankey diagrams provide an immediate, intuitive visual grasp of complex quantitative relationships.</p>
        <p style="color: #a09d98; margin-bottom: 20px;">Unlike standard flowcharts or organizational trees where arrows simply denote directional sequence or hierarchical subordination, every link in a Sankey diagram carries a rigorous numerical magnitude. If a stream representing 100 megawatts of electricity splits into two sub-streams of 70 megawatts and 30 megawatts, the combined physical width of the two outgoing arrows will exactly equal the width of the incoming arrow.</p>
        <ul style="color: #a09d98; margin-bottom: 32px; padding-left: 20px;">
          <li style="margin-bottom: 10px;"><strong>Nodes:</strong> Represent entities, states, processes, or accounts where flow originates, transforms, or terminates.</li>
          <li style="margin-bottom: 10px;"><strong>Links (Bands):</strong> Represent the quantitative transfer between two nodes. Their thickness is strictly proportional to numerical magnitude.</li>
          <li style="margin-bottom: 10px;"><strong>Sources &amp; Sinks:</strong> Nodes with only outgoing links are primary sources; nodes with only incoming links are final sinks or losses.</li>
        </ul>

        <h2 style="font-size: 26px; margin-top: 40px; margin-bottom: 16px;">2. The Origins: Captain Sankey and Minard's Masterpiece</h2>
        <p style="color: #a09d98; margin-bottom: 20px;">While modern web developers and data analysts frequently use Sankey diagrams for digital analytics, the visualization technique originated in late 19th-century mechanical and thermal engineering. The diagram is named after Irish-born Captain Matthew Henry Phineas Riall Sankey (1853–1926), an engineer who served in the Royal Engineers before retiring to pursue civil and mechanical engineering consulting.</p>
        <p style="color: #a09d98; margin-bottom: 20px;">In 1898, Captain Sankey published a landmark paper in the Minutes of Proceedings of the Institution of Civil Engineers titled "The Thermal Efficiency of Steam-Engines." To demonstrate why contemporary steam engines wasted the vast majority of their fuel energy, Sankey devised a chart showing the flow of heat energy from the boiler combustion chamber through the steam pipes, cylinder work, and condenser exhaust. By scaling the band thickness to British Thermal Units (BTUs), his chart made a dramatic visual statement: over 80% of the input fuel energy was lost as waste heat before performing useful mechanical work.</p>

        <h2 style="font-size: 26px; margin-top: 40px; margin-bottom: 16px;">3. Mathematical Foundations: Graph Theory &amp; Flow Conservation</h2>
        <p style="color: #a09d98; margin-bottom: 20px;">From a mathematical perspective, a Sankey diagram is a weighted, directed graph G = (V, E), where V represents the set of nodes and E represents the set of directed edges (links). Each edge e = (u, v) in E is assigned a strictly positive weight w(e) &gt; 0 representing the flow volume.</p>
        <p style="color: #a09d98; margin-bottom: 20px;">To maintain visual integrity and physical realism, well-designed Sankey diagrams adhere to the Principle of Flow Conservation (also known in physics as Kirchhoff's Current Law or the Continuity Equation). For any intermediate node v that is neither a pure primary source nor a final sink, the sum of all incoming flows must precisely match the sum of all outgoing flows: Σ w(u, v) = Σ w(v, z).</p>

        <h2 style="font-size: 26px; margin-top: 40px; margin-bottom: 16px;">4. Best Practices in Modern Data Visualization</h2>
        <p style="color: #a09d98; margin-bottom: 20px;">When designing quantitative flow charts, clarity and precision are paramount. Always minimize link crossovers by ordering nodes systematically, maintain consistent measurement units (e.g., megawatts, dollars, or metric tons) across the entire canvas, and group minor secondary flows into aggregated categories where appropriate to prevent visual clutter.</p>
      </main>
      <footer style="padding: 32px 48px; background: #0c0c0b; border-top: 1px solid #272521; color: #a09d98; font-family: sans-serif; font-size: 12px; text-align: center;">
        <p>© 2026 SankeyLoop. All rights reserved. <a href="/privacy" style="color: #a09d98;">Privacy Policy</a> | <a href="/terms" style="color: #a09d98;">Terms of Service</a> | <a href="/about" style="color: #a09d98;">About Us</a> | <a href="/contact" style="color: #a09d98;">Contact</a></p>
      </footer>
    `
  },
  {
    route: '/learn/energy-efficiency-heat-balance',
    title: 'Sankey Diagrams for Energy Efficiency & Thermodynamic Heat Balances - SankeyLoop',
    desc: 'How thermal engineers use Sankey diagrams to model boiler enthalpy flows, waste heat recovery, exergy destruction, and HVAC building energy balances.',
    content: `
      <header style="padding: 24px 48px; background: #0c0c0b; border-bottom: 1px solid #272521; color: #f0ede8; font-family: sans-serif; display: flex; justify-content: space-between; align-items: center;">
        <a href="/" style="font-size: 18px; font-weight: bold; color: #f0ede8; text-decoration: none;">Sankey<span style="color: #e8541a;">Loop</span></a>
        <nav style="display: flex; gap: 20px;">
          <a href="/" style="color: #a09d98; text-decoration: none; font-size: 14px;">Home</a>
          <a href="/learn" style="color: #e8541a; text-decoration: none; font-size: 14px;">Tutorials &amp; Guides</a>
          <a href="/about" style="color: #a09d98; text-decoration: none; font-size: 14px;">About</a>
          <a href="/privacy" style="color: #a09d98; text-decoration: none; font-size: 14px;">Privacy</a>
          <a href="/contact" style="color: #a09d98; text-decoration: none; font-size: 14px;">Contact</a>
          <a href="/app" style="color: #fff; background: #e8541a; padding: 6px 14px; border-radius: 4px; text-decoration: none; font-size: 14px;">Open Editor →</a>
        </nav>
      </header>
      <main style="padding: 48px; max-width: 900px; margin: 0 auto; color: #f0ede8; font-family: sans-serif; line-height: 1.7;">
        <div style="margin-bottom: 32px;"><a href="/learn" style="color: #ff813f; text-decoration: none; font-size: 14px;">← Back to Learning Hub</a></div>
        <span style="color: #ff813f; font-size: 12px; font-weight: bold; text-transform: uppercase;">Engineering • 14 min read</span>
        <h1 style="font-size: 40px; margin-top: 12px; margin-bottom: 24px;">Sankey Diagrams for Energy Efficiency &amp; Thermodynamic Heat Balances</h1>
        <p style="color: #a09d98; font-size: 18px; margin-bottom: 40px;">How thermal engineers use Sankey diagrams to model boiler enthalpy flows, waste heat recovery, exergy destruction, and HVAC building energy balances.</p>
        
        <h2 style="font-size: 26px; margin-top: 40px; margin-bottom: 16px;">1. First Law vs. Second Law Thermodynamic Efficiency</h2>
        <p style="color: #a09d98; margin-bottom: 20px;">In industrial energy management, evaluating thermal performance requires distinguishing between First Law enthalpy conservation and Second Law exergy preservation. The First Law of Thermodynamics states that energy cannot be created or destroyed; therefore, total energy input must equal total energy output plus stored energy. However, standard First Law balances often fail to capture the degradation of energy quality.</p>
        <p style="color: #a09d98; margin-bottom: 20px;">Sankey diagrams traditionally visualize First Law balances by mapping quantitative heat streams across boilers, turbines, condensers, and process vessels. When coupled with SankeyLoop's unique thermal gradient coloring, engineers can simultaneously visualize exergy destruction by encoding the temperature of each stream into the visual color palette.</p>

        <h2 style="font-size: 26px; margin-top: 40px; margin-bottom: 16px;">2. Industrial Boiler &amp; Steam Recovery Balances</h2>
        <p style="color: #a09d98; margin-bottom: 20px;">In typical manufacturing and chemical refining operations, industrial boilers convert fossil fuel or biomass chemical energy into high-pressure steam. Without visual flow mapping, minor thermal inefficiencies across blowdown discharge, uninsulated pipe radiation, and stack gas exhaust can remain hidden inside complex operational logs.</p>
        <p style="color: #a09d98; margin-bottom: 20px;">By modeling the boiler system as an interconnected Sankey network, plant engineers can quantify the exact BTU contribution of economizers, air preheaters, and closed-loop condensate return lines, identifying opportunities to recover up to 15-25% of wasted thermal energy.</p>

        <h2 style="font-size: 26px; margin-top: 40px; margin-bottom: 16px;">3. Building HVAC &amp; Decarbonization Audits</h2>
        <p style="color: #a09d98; margin-bottom: 20px;">Commercial and residential buildings account for nearly 40% of global energy consumption. Mapping building energy flows from utility grid intake and natural gas service through chiller loops, variable refrigerant flow (VRF) units, and lighting circuits allows sustainability officers to prioritize retrofit capital expenditures based on measured exergy impact.</p>
      </main>
      <footer style="padding: 32px 48px; background: #0c0c0b; border-top: 1px solid #272521; color: #a09d98; font-family: sans-serif; font-size: 12px; text-align: center;">
        <p>© 2026 SankeyLoop. All rights reserved. <a href="/privacy" style="color: #a09d98;">Privacy Policy</a> | <a href="/terms" style="color: #a09d98;">Terms of Service</a> | <a href="/about" style="color: #a09d98;">About Us</a> | <a href="/contact" style="color: #a09d98;">Contact</a></p>
      </footer>
    `
  },
  {
    route: '/learn/financial-cash-flow-budgeting',
    title: 'Visualizing Corporate Cash Flow & P&L Statements with Sankey Diagrams - SankeyLoop',
    desc: 'Transform GAAP income statements and SaaS revenue funnels into clear financial waterfalls. Model gross revenue, COGS, R&D overhead, and net margin retention.',
    content: `
      <header style="padding: 24px 48px; background: #0c0c0b; border-bottom: 1px solid #272521; color: #f0ede8; font-family: sans-serif; display: flex; justify-content: space-between; align-items: center;">
        <a href="/" style="font-size: 18px; font-weight: bold; color: #f0ede8; text-decoration: none;">Sankey<span style="color: #e8541a;">Loop</span></a>
        <nav style="display: flex; gap: 20px;">
          <a href="/" style="color: #a09d98; text-decoration: none; font-size: 14px;">Home</a>
          <a href="/learn" style="color: #e8541a; text-decoration: none; font-size: 14px;">Tutorials &amp; Guides</a>
          <a href="/about" style="color: #a09d98; text-decoration: none; font-size: 14px;">About</a>
          <a href="/privacy" style="color: #a09d98; text-decoration: none; font-size: 14px;">Privacy</a>
          <a href="/contact" style="color: #a09d98; text-decoration: none; font-size: 14px;">Contact</a>
          <a href="/app" style="color: #fff; background: #e8541a; padding: 6px 14px; border-radius: 4px; text-decoration: none; font-size: 14px;">Open Editor →</a>
        </nav>
      </header>
      <main style="padding: 48px; max-width: 900px; margin: 0 auto; color: #f0ede8; font-family: sans-serif; line-height: 1.7;">
        <div style="margin-bottom: 32px;"><a href="/learn" style="color: #ff813f; text-decoration: none; font-size: 14px;">← Back to Learning Hub</a></div>
        <span style="color: #ff813f; font-size: 12px; font-weight: bold; text-transform: uppercase;">Finance • 11 min read</span>
        <h1 style="font-size: 40px; margin-top: 12px; margin-bottom: 24px;">Visualizing Corporate Cash Flow &amp; P&amp;L Statements with Sankey Diagrams</h1>
        <p style="color: #a09d98; font-size: 18px; margin-bottom: 40px;">Transform GAAP income statements and SaaS revenue funnels into clear financial waterfalls. Model gross revenue, COGS, R&amp;D overhead, and net margin retention.</p>
        
        <h2 style="font-size: 26px; margin-top: 40px; margin-bottom: 16px;">1. Beyond Double-Entry Spreadsheets: The Power of Financial Waterfalls</h2>
        <p style="color: #a09d98; margin-bottom: 20px;">While double-entry accounting spreadsheets provide necessary granular transaction records, they often fail to communicate macro-level financial narratives to executive leaders, board members, and external investors. When analyzing complex Profit &amp; Loss (P&amp;L) statements, stakeholders need to instantly see how gross revenue inflows split and cascade down through cost structures.</p>
        <p style="color: #a09d98; margin-bottom: 20px;">By structuring corporate financial accounts as a directed Sankey network, CFOs can present a complete visual waterfall where the thickness of each stream corresponds precisely to dollar amounts, clearly isolating major operating expenditures from net EBITDA profit retention.</p>

        <h2 style="font-size: 26px; margin-top: 40px; margin-bottom: 16px;">2. SaaS Cohort Dynamics &amp; Unit Economics</h2>
        <p style="color: #a09d98; margin-bottom: 20px;">In subscription business models and SaaS analytics, tracking customer retention, expansion revenue, contraction, and churn across customer cohorts is vital for sustainable growth. Sankey diagrams allow growth leaders to model exact customer journeys from initial marketing leads through trial conversions, paid tier upgrades, and net revenue retention.</p>
      </main>
      <footer style="padding: 32px 48px; background: #0c0c0b; border-top: 1px solid #272521; color: #a09d98; font-family: sans-serif; font-size: 12px; text-align: center;">
        <p>© 2026 SankeyLoop. All rights reserved. <a href="/privacy" style="color: #a09d98;">Privacy Policy</a> | <a href="/terms" style="color: #a09d98;">Terms of Service</a> | <a href="/about" style="color: #a09d98;">About Us</a> | <a href="/contact" style="color: #a09d98;">Contact</a></p>
      </footer>
    `
  },
  {
    route: '/learn/sankeyloop-user-manual',
    title: 'SankeyLoop Editor User Manual & Technical Documentation - SankeyLoop',
    desc: 'Complete documentation for SankeyLoop: natural language syntax rules, Excel drag-and-drop table formatting, custom node positioning, and vector export options.',
    content: `
      <header style="padding: 24px 48px; background: #0c0c0b; border-bottom: 1px solid #272521; color: #f0ede8; font-family: sans-serif; display: flex; justify-content: space-between; align-items: center;">
        <a href="/" style="font-size: 18px; font-weight: bold; color: #f0ede8; text-decoration: none;">Sankey<span style="color: #e8541a;">Loop</span></a>
        <nav style="display: flex; gap: 20px;">
          <a href="/" style="color: #a09d98; text-decoration: none; font-size: 14px;">Home</a>
          <a href="/learn" style="color: #e8541a; text-decoration: none; font-size: 14px;">Tutorials &amp; Guides</a>
          <a href="/about" style="color: #a09d98; text-decoration: none; font-size: 14px;">About</a>
          <a href="/privacy" style="color: #a09d98; text-decoration: none; font-size: 14px;">Privacy</a>
          <a href="/contact" style="color: #a09d98; text-decoration: none; font-size: 14px;">Contact</a>
          <a href="/app" style="color: #fff; background: #e8541a; padding: 6px 14px; border-radius: 4px; text-decoration: none; font-size: 14px;">Open Editor →</a>
        </nav>
      </header>
      <main style="padding: 48px; max-width: 900px; margin: 0 auto; color: #f0ede8; font-family: sans-serif; line-height: 1.7;">
        <div style="margin-bottom: 32px;"><a href="/learn" style="color: #ff813f; text-decoration: none; font-size: 14px;">← Back to Learning Hub</a></div>
        <span style="color: #ff813f; font-size: 12px; font-weight: bold; text-transform: uppercase;">Documentation • 10 min read</span>
        <h1 style="font-size: 40px; margin-top: 12px; margin-bottom: 24px;">SankeyLoop Editor User Manual &amp; Technical Documentation</h1>
        <p style="color: #a09d98; font-size: 18px; margin-bottom: 40px;">Complete documentation for SankeyLoop: natural language syntax rules, Excel drag-and-drop table formatting, custom node positioning, and vector export options.</p>
        
        <h2 style="font-size: 26px; margin-top: 40px; margin-bottom: 16px;">1. Natural Language Syntax Specification</h2>
        <p style="color: #a09d98; margin-bottom: 20px;">SankeyLoop utilizes a clean, human-readable syntax engine that enables rapid flow specification without coding. Each line in the editor text area represents a directed link connecting a source node to a target node with a specified numeric quantity.</p>
        <p style="color: #a09d98; margin-bottom: 20px;">Syntax format: <code>Source [Amount] Target #ColorOrTemperature</code>. For example: <code>Gas Boiler [85] Steam Pipe #FF4500</code> creates an 85-unit flow from Gas Boiler to Steam Pipe colored with an orange/red thermal code.</p>

        <h2 style="font-size: 26px; margin-top: 40px; margin-bottom: 16px;">2. Copy-Paste from Microsoft Excel &amp; Google Sheets</h2>
        <p style="color: #a09d98; margin-bottom: 20px;">If your data is currently stored in spreadsheet software, you can highlight columns containing Source, Target, and Value cells, copy them directly (<code>Ctrl+C</code>), and paste them straight into SankeyLoop (<code>Ctrl+V</code>). The parsing engine automatically detects tab-separated and comma-separated formats and converts them into valid flow relationships.</p>

        <h2 style="font-size: 26px; margin-top: 40px; margin-bottom: 16px;">3. Export &amp; Publication Settings</h2>
        <p style="color: #a09d98; margin-bottom: 20px;">Once your layout is complete, you can export your diagram at up to 3x raster scaling as a PNG image, or as a lossless Scalable Vector Graphics (SVG) file suitable for direct insertion into academic publications, corporate reports, and vector editing suites like Adobe Illustrator.</p>
      </main>
      <footer style="padding: 32px 48px; background: #0c0c0b; border-top: 1px solid #272521; color: #a09d98; font-family: sans-serif; font-size: 12px; text-align: center;">
        <p>© 2026 SankeyLoop. All rights reserved. <a href="/privacy" style="color: #a09d98;">Privacy Policy</a> | <a href="/terms" style="color: #a09d98;">Terms of Service</a> | <a href="/about" style="color: #a09d98;">About Us</a> | <a href="/contact" style="color: #a09d98;">Contact</a></p>
      </footer>
    `
  },
  {
    route: '/about',
    title: 'About SankeyLoop - Mission, Privacy, and Quantitative Engineering',
    desc: 'Learn about the mission of SankeyLoop, independent engineering development, and why we built a 100% client-side, local-first flow visualization tool.',
    content: `
      <header style="padding: 24px 48px; background: #0c0c0b; border-bottom: 1px solid #272521; color: #f0ede8; font-family: sans-serif; display: flex; justify-content: space-between; align-items: center;">
        <a href="/" style="font-size: 18px; font-weight: bold; color: #f0ede8; text-decoration: none;">Sankey<span style="color: #e8541a;">Loop</span></a>
        <nav style="display: flex; gap: 20px;">
          <a href="/" style="color: #a09d98; text-decoration: none; font-size: 14px;">Home</a>
          <a href="/learn" style="color: #a09d98; text-decoration: none; font-size: 14px;">Tutorials &amp; Guides</a>
          <a href="/about" style="color: #e8541a; text-decoration: none; font-size: 14px;">About</a>
          <a href="/privacy" style="color: #a09d98; text-decoration: none; font-size: 14px;">Privacy</a>
          <a href="/contact" style="color: #a09d98; text-decoration: none; font-size: 14px;">Contact</a>
          <a href="/app" style="color: #fff; background: #e8541a; padding: 6px 14px; border-radius: 4px; text-decoration: none; font-size: 14px;">Open Editor →</a>
        </nav>
      </header>
      <main style="padding: 48px; max-width: 900px; margin: 0 auto; color: #f0ede8; font-family: sans-serif; line-height: 1.7;">
        <h1 style="font-size: 40px; margin-bottom: 24px;">About SankeyLoop</h1>
        <p style="color: #a09d98; font-size: 18px; margin-bottom: 32px;">SankeyLoop is a specialized, independent data visualization platform built to make high-precision quantitative flow modeling accessible, private, and intuitive.</p>
        
        <h2 style="font-size: 26px; margin-top: 32px; margin-bottom: 16px;">Our Engineering Philosophy</h2>
        <p style="color: #a09d98; margin-bottom: 20px;">Sankey diagrams have been essential tools since Captain Matthew Sankey mapped steam engine efficiency in 1898. However, modern software tools often force users into two undesirable extremes: complicated programming libraries that require extensive coding, or basic online tools that upload proprietary corporate data to external cloud servers.</p>
        <p style="color: #a09d98; margin-bottom: 20px;">We created SankeyLoop to bridge this gap. By combining a natural language syntax engine with a 100% client-side browser execution architecture, SankeyLoop delivers professional engineering and financial visualization capabilities without compromising data privacy or ease of use.</p>
      </main>
      <footer style="padding: 32px 48px; background: #0c0c0b; border-top: 1px solid #272521; color: #a09d98; font-family: sans-serif; font-size: 12px; text-align: center;">
        <p>© 2026 SankeyLoop. All rights reserved. <a href="/privacy" style="color: #a09d98;">Privacy Policy</a> | <a href="/terms" style="color: #a09d98;">Terms of Service</a> | <a href="/about" style="color: #a09d98;">About Us</a> | <a href="/contact" style="color: #a09d98;">Contact</a></p>
      </footer>
    `
  },
  {
    route: '/privacy',
    title: 'Privacy Policy - SankeyLoop',
    desc: 'Our strict client-side data commitment: SankeyLoop operates 100% locally inside your browser. No diagram data ever leaves your device or touches cloud storage.',
    content: `
      <header style="padding: 24px 48px; background: #0c0c0b; border-bottom: 1px solid #272521; color: #f0ede8; font-family: sans-serif; display: flex; justify-content: space-between; align-items: center;">
        <a href="/" style="font-size: 18px; font-weight: bold; color: #f0ede8; text-decoration: none;">Sankey<span style="color: #e8541a;">Loop</span></a>
        <nav style="display: flex; gap: 20px;">
          <a href="/" style="color: #a09d98; text-decoration: none; font-size: 14px;">Home</a>
          <a href="/learn" style="color: #a09d98; text-decoration: none; font-size: 14px;">Tutorials &amp; Guides</a>
          <a href="/about" style="color: #a09d98; text-decoration: none; font-size: 14px;">About</a>
          <a href="/privacy" style="color: #e8541a; text-decoration: none; font-size: 14px;">Privacy</a>
          <a href="/contact" style="color: #a09d98; text-decoration: none; font-size: 14px;">Contact</a>
          <a href="/app" style="color: #fff; background: #e8541a; padding: 6px 14px; border-radius: 4px; text-decoration: none; font-size: 14px;">Open Editor →</a>
        </nav>
      </header>
      <main style="padding: 48px; max-width: 900px; margin: 0 auto; color: #f0ede8; font-family: sans-serif; line-height: 1.7;">
        <h1 style="font-size: 40px; margin-bottom: 24px;">Privacy Policy</h1>
        <p style="color: #a09d98; font-size: 18px; margin-bottom: 32px;">At SankeyLoop, we believe that data visualization tools should never require you to sacrifice the confidentiality of your financial or engineering measurements.</p>
        
        <h2 style="font-size: 26px; margin-top: 32px; margin-bottom: 16px;">1. Client-Side Data Execution Architecture</h2>
        <p style="color: #a09d98; margin-bottom: 20px;">SankeyLoop operates purely as a client-side web application. When you input flow data into our editor, your numbers and labels are processed directly by your computer's local processor. Your proprietary data is never sent to our servers, never transmitted across the internet, and never stored in any cloud database.</p>

        <h2 style="font-size: 26px; margin-top: 32px; margin-bottom: 16px;">2. Local Storage &amp; Cookies</h2>
        <p style="color: #a09d98; margin-bottom: 20px;">We use standard HTML5 local storage to save your user preferences and your current diagram work directly within your web browser so you can resume sessions seamlessly. Third-party advertising vendors, including Google AdSense, use cookies to serve advertisements based on prior visits to this website and other sites across the internet.</p>
        <p style="color: #a09d98; margin-bottom: 20px;">You can opt out of personalized advertising by visiting Google's Ads Settings at https://www.google.com/settings/ads.</p>
      </main>
      <footer style="padding: 32px 48px; background: #0c0c0b; border-top: 1px solid #272521; color: #a09d98; font-family: sans-serif; font-size: 12px; text-align: center;">
        <p>© 2026 SankeyLoop. All rights reserved. <a href="/privacy" style="color: #a09d98;">Privacy Policy</a> | <a href="/terms" style="color: #a09d98;">Terms of Service</a> | <a href="/about" style="color: #a09d98;">About Us</a> | <a href="/contact" style="color: #a09d98;">Contact</a></p>
      </footer>
    `
  },
  {
    route: '/terms',
    title: 'Terms of Service - SankeyLoop',
    desc: 'Terms and conditions for using SankeyLoop, including license terms for exported diagrams, vector graphics, and open-source usage.',
    content: `
      <header style="padding: 24px 48px; background: #0c0c0b; border-bottom: 1px solid #272521; color: #f0ede8; font-family: sans-serif; display: flex; justify-content: space-between; align-items: center;">
        <a href="/" style="font-size: 18px; font-weight: bold; color: #f0ede8; text-decoration: none;">Sankey<span style="color: #e8541a;">Loop</span></a>
        <nav style="display: flex; gap: 20px;">
          <a href="/" style="color: #a09d98; text-decoration: none; font-size: 14px;">Home</a>
          <a href="/learn" style="color: #a09d98; text-decoration: none; font-size: 14px;">Tutorials &amp; Guides</a>
          <a href="/about" style="color: #a09d98; text-decoration: none; font-size: 14px;">About</a>
          <a href="/privacy" style="color: #a09d98; text-decoration: none; font-size: 14px;">Privacy</a>
          <a href="/terms" style="color: #e8541a; text-decoration: none; font-size: 14px;">Terms</a>
          <a href="/contact" style="color: #a09d98; text-decoration: none; font-size: 14px;">Contact</a>
          <a href="/app" style="color: #fff; background: #e8541a; padding: 6px 14px; border-radius: 4px; text-decoration: none; font-size: 14px;">Open Editor →</a>
        </nav>
      </header>
      <main style="padding: 48px; max-width: 900px; margin: 0 auto; color: #f0ede8; font-family: sans-serif; line-height: 1.7;">
        <h1 style="font-size: 40px; margin-bottom: 24px;">Terms of Service</h1>
        <p style="color: #a09d98; font-size: 18px; margin-bottom: 32px;">By accessing or using the SankeyLoop web application, you agree to comply with and be bound by the following Terms of Service.</p>
        
        <h2 style="font-size: 26px; margin-top: 32px; margin-bottom: 16px;">1. Usage Rights &amp; Ownership of Diagrams</h2>
        <p style="color: #a09d98; margin-bottom: 20px;">You retain 100% copyright and intellectual property ownership over any Sankey diagrams, images, vector graphics, or data tables you create using SankeyLoop. You are free to use generated diagrams for personal, academic, institutional, or commercial publications without attribution or watermarks.</p>
      </main>
      <footer style="padding: 32px 48px; background: #0c0c0b; border-top: 1px solid #272521; color: #a09d98; font-family: sans-serif; font-size: 12px; text-align: center;">
        <p>© 2026 SankeyLoop. All rights reserved. <a href="/privacy" style="color: #a09d98;">Privacy Policy</a> | <a href="/terms" style="color: #a09d98;">Terms of Service</a> | <a href="/about" style="color: #a09d98;">About Us</a> | <a href="/contact" style="color: #a09d98;">Contact</a></p>
      </footer>
    `
  },
  {
    route: '/contact',
    title: 'Contact Us & Support - SankeyLoop',
    desc: 'Get in touch with the SankeyLoop development team for technical inquiries, feature suggestions, or institutional support.',
    content: `
      <header style="padding: 24px 48px; background: #0c0c0b; border-bottom: 1px solid #272521; color: #f0ede8; font-family: sans-serif; display: flex; justify-content: space-between; align-items: center;">
        <a href="/" style="font-size: 18px; font-weight: bold; color: #f0ede8; text-decoration: none;">Sankey<span style="color: #e8541a;">Loop</span></a>
        <nav style="display: flex; gap: 20px;">
          <a href="/" style="color: #a09d98; text-decoration: none; font-size: 14px;">Home</a>
          <a href="/learn" style="color: #a09d98; text-decoration: none; font-size: 14px;">Tutorials &amp; Guides</a>
          <a href="/about" style="color: #a09d98; text-decoration: none; font-size: 14px;">About</a>
          <a href="/privacy" style="color: #a09d98; text-decoration: none; font-size: 14px;">Privacy</a>
          <a href="/contact" style="color: #e8541a; text-decoration: none; font-size: 14px;">Contact</a>
          <a href="/app" style="color: #fff; background: #e8541a; padding: 6px 14px; border-radius: 4px; text-decoration: none; font-size: 14px;">Open Editor →</a>
        </nav>
      </header>
      <main style="padding: 48px; max-width: 900px; margin: 0 auto; color: #f0ede8; font-family: sans-serif; line-height: 1.7;">
        <h1 style="font-size: 40px; margin-bottom: 24px;">Contact Us</h1>
        <p style="color: #a09d98; font-size: 18px; margin-bottom: 32px;">We welcome feedback, bug reports, feature suggestions, and educational collaboration inquiries from engineers and researchers worldwide.</p>
        <p style="color: #a09d98; margin-bottom: 20px;">To reach the SankeyLoop maintainers directly, please email our engineering desk or connect through our GitHub repository. We aim to respond to technical inquiries within 48 hours.</p>
      </main>
      <footer style="padding: 32px 48px; background: #0c0c0b; border-top: 1px solid #272521; color: #a09d98; font-family: sans-serif; font-size: 12px; text-align: center;">
        <p>© 2026 SankeyLoop. All rights reserved. <a href="/privacy" style="color: #a09d98;">Privacy Policy</a> | <a href="/terms" style="color: #a09d98;">Terms of Service</a> | <a href="/about" style="color: #a09d98;">About Us</a> | <a href="/contact" style="color: #a09d98;">Contact</a></p>
      </footer>
    `
  }
];

let generatedCount = 0;

for (const page of pages) {
  const targetDir = path.join(distDir, page.route.replace(/^\//, ''));
  fs.mkdirSync(targetDir, { recursive: true });

  let pageHtml = baseHtml;
  // Replace title
  pageHtml = pageHtml.replace(/<title>.*?<\/title>/, `<title>${page.title}</title>`);
  // Insert or update description
  if (pageHtml.includes('<meta name="description"')) {
    pageHtml = pageHtml.replace(/<meta name="description".*?>/, `<meta name="description" content="${page.desc}" />`);
  } else {
    pageHtml = pageHtml.replace(/<\/head>/, `  <meta name="description" content="${page.desc}" />\n  </head>`);
  }

  // Replace content inside #root
  pageHtml = pageHtml.replace(/<div id="root">[\s\S]*?<\/div>\s*<script/, `<div id="root">${page.content}</div>\n    <script`);

  const targetPath = path.join(targetDir, 'index.html');
  fs.writeFileSync(targetPath, pageHtml, 'utf-8');
  generatedCount++;
  console.log(`Generated static prerendered HTML for: ${page.route} -> ${path.relative(distDir, targetPath)}`);
}

console.log(`Successfully generated ${generatedCount} static HTML pages inside dist/!`);
